#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         5
bspc config window_gap           0
bspc config normal_border_color  \#7F7F7F
#bspc config active_border_color  \#000000
bspc config focused_border_color \#FFFF00
bspc config top_padding 25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
picom --experimental-backends -b
#picom -b
#~/.config/polybar/launch.sh
