autocmd VimEnter * hi Normal ctermbg=NONE guibg=NONE
colorscheme gruvbox
filetype on
nnoremap <space> @=((foldclosed(line('.')) < 0) ? 'zc' : 'zo')<CR> " 用空格键来开关折叠
set autochdir " 自动切换当前目录为当前文件所在的目录
set background=dark    " Setting dark mode
set backspace=indent,eol,start " 不设定在插入状态无法用退格键和 Delete 键删除回车符
set backupcopy=yes " 设置备份时的行为为覆盖
set bufhidden=hide " 当buffer被丢弃的时候隐藏它
set cmdheight=1 " 设定命令行的行数为 1
set cursorline " 突出显示当前行
set expandtab "用空格代替制表符 
set foldcolumn=0 " 设置折叠区域的宽度
set foldenable " 开始折叠
set foldmethod=syntax " 设置语法折叠
set hlsearch " 搜索时高亮显示被找到的文本
set laststatus=2 " 显示状态栏 (默认值为 1, 无法显示状态栏)
set magic " 设置魔术
set matchtime=2 " 短暂跳转到匹配括号的时间
set nobackup " 覆盖文件时不备份
set nocompatible "use vim keys not vi mode
set noerrorbells " 关闭错误信息响铃
set novisualbell " 关闭使用可视响铃代替呼叫
set number " 显示行号
set ruler " 打开状态栏标尺
set shiftwidth=4 " 设定 << 和 >> 命令移动时的宽度为 4
set showmatch "高亮显示匹配的括号
set smartindent " 开启新行时使用智能自动缩进
set smarttab "智能TAB
set softtabstop=4 " 使得按退格键时可以一次删掉 4 个空格
set statusline=\ %<%F[%1*%M%*%n%R%H]%=\ %y\ %0(%{&fileformat}\ %{&encoding}\ Ln\ %l,\ Col\ %c/%L%) " 设置在状态行显示的信息
set t_vb= " 置空错误铃声的终端代码
set tabstop=4 " 设定 tab 长度为 4
setlocal foldlevel=1 " 设置折叠层数为 1
setlocal noswapfile " 不要生成swap文件
syntax on "syntax highlight
